local   all             postgres                                trust
local   all             all                                     trust
hostnossl all           all             all                     reject
hostssl finance         database        all                     cert clientcert=verify-full